# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7E0CdZXaS8ueJ_guv3gR8OqQbqy4bGO
"""

import imageio
import numpy as np
import matplotlib.pyplot as plt

def read_image(image_path):
    image = imageio.v3.imread(image_path)
    return image

def show_image(image, title):
    plt.imshow(image, cmap='gray')
    plt.title(title)
    plt.axis('off')
    plt.show()

def encrypt_image(image, key):
    key_resized = np.resize(key, image.shape)
    encrypted_image = np.bitwise_xor(image, key_resized)
    return encrypted_image

def decrypt_image(encrypted_image, key):
    key_resized = np.resize(key, encrypted_image.shape)
    decrypted_image = np.bitwise_xor(encrypted_image, key_resized)
    return decrypted_image


def main():

    image_path = 'image.png'

    original_image = read_image(image_path)

    if len(original_image.shape) == 3:
        original_image = np.mean(original_image, axis=2).astype(np.uint8)

    show_image(original_image, "Original Image")

    np.random.seed(42)
    key = np.random.randint(0, 256, size=(original_image.shape), dtype=np.uint8)

    encrypted_image = encrypt_image(original_image, key)
    show_image(encrypted_image, "Encrypted Image")

    decrypted_image = decrypt_image(encrypted_image, key)
    show_image(decrypted_image, "Decrypted Image")

    imageio.v3.imwrite('encrypted_image.png', encrypted_image)
    imageio.v3.imwrite('decrypted_image.png', decrypted_image)

if __name__ == "__main__":
    main()